/** Mirrored from Prisma schema for use in API and web without Prisma dependency. */

export const UserType = {
  SYSTEM_USER: "SYSTEM_USER",
} as const

export type UserType = (typeof UserType)[keyof typeof UserType]

export const Role = {
  ADMIN: "ADMIN",
  USER: "USER",
  SALE: "SALE",
  PUMPIST: "PUMPIST",
} as const

export type Role = (typeof Role)[keyof typeof Role]

export const ShiftStatus = {
  PLANNED: "PLANNED",
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  RECONCILED: "RECONCILED",
} as const

export type ShiftStatus = (typeof ShiftStatus)[keyof typeof ShiftStatus]

export const ShopSalesSource = {
  SHIFT_SUMMARY_ENTRY: "SHIFT_SUMMARY_ENTRY",
  TRANSACTIONAL_SYSTEM_TOTAL: "TRANSACTIONAL_SYSTEM_TOTAL",
  MANUAL: "MANUAL",
} as const

export type ShopSalesSource =
  (typeof ShopSalesSource)[keyof typeof ShopSalesSource]

export const EventType = {
  SHIFT_CREATED: "SHIFT_CREATED",
  SHIFT_UPDATED: "SHIFT_UPDATED",
  SHIFT_STATUS_CHANGED: "SHIFT_STATUS_CHANGED",
  SHIFT_STOCK_UPSERTED: "SHIFT_STOCK_UPSERTED",
  PUMP_READING_RECORDED: "PUMP_READING_RECORDED",
  PUMP_READING_UPDATED: "PUMP_READING_UPDATED",
  CASH_HAND_IN_RECORDED: "CASH_HAND_IN_RECORDED",
  CASH_HAND_IN_UPDATED: "CASH_HAND_IN_UPDATED",
  CASH_HAND_IN_DELETED: "CASH_HAND_IN_DELETED",
  RECONCILIATION_CREATED: "RECONCILIATION_CREATED",
  RECONCILIATION_UPDATED: "RECONCILIATION_UPDATED",
  FUEL_DELIVERY_RECORDED: "FUEL_DELIVERY_RECORDED",
  TANK_LEVEL_READING_RECORDED: "TANK_LEVEL_READING_RECORDED",
  FUEL_PRICE_SET: "FUEL_PRICE_SET",
  PURCHASE_PRICE_SET: "PURCHASE_PRICE_SET",
  WEEKLY_INVENTORY_CLOSE_RECORDED: "WEEKLY_INVENTORY_CLOSE_RECORDED",
  EXPENSE_RECORDED: "EXPENSE_RECORDED",
  EXPENSE_UPDATED: "EXPENSE_UPDATED",
  EXPENSE_DELETED: "EXPENSE_DELETED",
  CASH_DEPOSIT_RECORDED: "CASH_DEPOSIT_RECORDED",
  CASH_DEPOSIT_UPDATED: "CASH_DEPOSIT_UPDATED",
  CASH_DEPOSIT_DELETED: "CASH_DEPOSIT_DELETED",
  SHORTAGE_SETTLED: "SHORTAGE_SETTLED",
  SETTING_UPDATED: "SETTING_UPDATED",
  SELLING_PRICE_SET: "SELLING_PRICE_SET",
} as const

export type EventType = (typeof EventType)[keyof typeof EventType]
